#!/usr/bin/env bash
# =============================================================================
# The ONE place that writes /etc/caddy/Caddyfile.
#
#   bash deploy/scripts/render-caddyfile.sh [--no-reload] [--staging]
#
# Reads deploy/site.env and generates the live config:
#   SITE_HOSTNAME empty  -> plain HTTP on :80          (raw EC2 IP, pre-cutover)
#   SITE_HOSTNAME set    -> that hostname with automatic TLS, and Caddy's own
#                           built-in 80 -> 443 redirect
#   ... plus --staging   -> BOTH AT ONCE, transiently. See below.
#
# --staging exists because of one specific way this cutover used to break the
# site. Going straight from `:80 {...}` to `$SITE_HOSTNAME {...}` in a single
# reload DELETES the plain-HTTP catch-all at the instant Caddy starts asking
# Let's Encrypt for a certificate it does not have yet. For those 10-30s (or for
# the full 4-minute timeout when issuance FAILS) every URL is dead: http://<IP>/
# 301s to https, http://<host>/ 308s to https (Caddy's automatic redirect), and
# https:// cannot complete a handshake because there is no certificate. That is
# a hard outage on a box running payroll, and if the operator Ctrl-Cs during it
# the box simply stays that way.
#
# With --staging the port-80 catch-all is kept EXACTLY as it is pre-cutover and
# an `https://$SITE_HOSTNAME` block is added alongside it. Caddy provisions the
# certificate for that block while plain HTTP keeps serving the app, so there is
# no window in which the site is unreachable. enable-https.sh renders --staging
# first, proves the certificate, and only then renders the final config — by
# which point the certificate is already in Caddy's storage, so the final reload
# is a normal zero-downtime reload.
#
# Caddy still answers the ACME HTTP-01 challenge during staging: the challenge
# routes are prepended to the port-80 server ahead of any user-defined routes,
# so the `handle` catch-all below cannot swallow them.
#
# --staging is a FLAG, never a setting in site.env: it must not survive into a
# later `install.sh`, or the box would keep serving the app over plain HTTP
# forever alongside HTTPS.
#
# The routing is IDENTICAL in both cases and is defined exactly once, below:
#   /procurement*  -> 127.0.0.1:3002   (built with basePath=/procurement, so the
#                                       prefix must SURVIVE -> `handle`, never
#                                       `handle_path`)
#   everything else-> 127.0.0.1:3009   (timesheet / payroll)
#
# Idempotent by construction: it regenerates the whole file every time and
# rewrites nothing if the result is byte-identical, so it can never append a
# duplicate site block. install.sh calls this at step [8].
# =============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"     # deploy/
DEST=/etc/caddy/Caddyfile
RELOAD=1
STAGING=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --no-reload) RELOAD=0 ;;
    --staging)   STAGING=1 ;;
    *) echo "render-caddyfile: unknown argument '$1' (want --no-reload and/or --staging)" >&2; exit 2 ;;
  esac
  shift
done

SITE_HOSTNAME=""; ACME_EMAIL=""; LEGACY_HTTP_HOST=""
if [ -f "$HERE/site.env" ]; then
  set -a
  # shellcheck source=/dev/null
  . "$HERE/site.env"
  set +a
fi

# --staging is only meaningful when there is a hostname to get a certificate for.
if [ "$STAGING" = "1" ] && [ -z "$SITE_HOSTNAME" ]; then
  echo "render-caddyfile: --staging needs SITE_HOSTNAME in deploy/site.env — refusing" >&2
  exit 2
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# The routing, defined ONCE and emitted into whichever site block(s) this render
# produces (two of them in --staging mode). Includes the site block's closing
# brace. Change routing here and nowhere else.
routes() {
  cat <<'ROUTES'
	encode gzip

	# basePath means the app EXPECTS /procurement in the path — use `handle`,
	# not `handle_path`, so the prefix is preserved rather than stripped.
	handle /procurement* {
		reverse_proxy 127.0.0.1:3002
	}

	handle {
		reverse_proxy 127.0.0.1:3009
	}
}
ROUTES
}

{
  echo "# GENERATED by deploy/scripts/render-caddyfile.sh — DO NOT EDIT BY HAND."
  echo "# Your edits will be overwritten by the next deploy (install.sh step 8)."
  echo "# Change the hostname in deploy/site.env; change the routing in that script."
  # Deliberately NO timestamp here: it would make every render differ from the
  # installed file, so the no-op check below could never fire and every deploy
  # would rewrite the config, take another backup and reload Caddy for nothing.
  echo
  if [ -n "$SITE_HOSTNAME" ] && [ -n "$ACME_EMAIL" ]; then
    echo "{"
    echo "	email $ACME_EMAIL"
    echo "}"
    echo
  fi
  if [ "$STAGING" = "1" ]; then
    # ---- TRANSIENT. Written only while a certificate is being issued. --------
    echo "# ⚠ TRANSIENT CONFIG — a cutover is IN PROGRESS. Not the final state."
    echo "#"
    echo "# The :80 block below is the pre-cutover config, kept BYTE-FOR-BYTE so the"
    echo "# site never stops answering while Let's Encrypt issues the certificate for"
    echo "# the https:// block. Without it there is a 10-30s window (up to 4 min on"
    echo "# failure) where http:// only redirects and https:// has no certificate —"
    echo "# i.e. every URL dead, on a box running payroll."
    echo "#"
    echo "# enable-https.sh replaces this with the final config as soon as the"
    echo "# certificate is proven. If you are reading this in the LIVE Caddyfile then"
    echo "# a cutover was interrupted: the site is UP but still served over plain"
    echo "# HTTP as well. Finish or undo it with"
    echo "#     bash deploy/scripts/render-caddyfile.sh"
    echo "# which re-renders the final config from deploy/site.env."
    echo
    echo ":80 {"
    routes
    echo
    echo "# The certificate this whole staging step exists to obtain. Explicit"
    echo "# https:// scheme, so Caddy does NOT add its automatic 80->443 redirect"
    echo "# and cannot shadow the plain-HTTP block above."
    echo "https://$SITE_HOSTNAME {"
    routes
  elif [ -n "$SITE_HOSTNAME" ]; then
    if [ -n "$LEGACY_HTTP_HOST" ]; then
      echo "# Grace period for old bookmarks and already-sent password-reset links."
      echo "# Redirect only — the app is never served over plain HTTP here."
      echo "http://$LEGACY_HTTP_HOST {"
      echo "	redir https://$SITE_HOSTNAME{uri} permanent"
      echo "}"
      echo
    fi
    echo "$SITE_HOSTNAME {"
    routes
  else
    echo "# No SITE_HOSTNAME in deploy/site.env — plain HTTP for the raw EC2 IP."
    echo "# Pair with COOKIE_SECURE=false in BOTH .env.production files, or the"
    echo "# login cookie is never sent back and sign-in silently fails."
    echo ":80 {"
    routes
  fi
} > "$TMP"

# Cheap guard against a hand-edit of this script losing a route: both apps must
# still be reachable, or a "successful" render silently 404s half the site.
# Counted, not just present: --staging emits TWO site blocks and each one has to
# carry the full routing, or half the traffic lands on a block that 404s.
WANT=1
if [ "$STAGING" = "1" ]; then WANT=2; fi
for pat in 'handle /procurement\*' '127\.0\.0\.1:3002' '127\.0\.0\.1:3009'; do
  n="$(grep -c "$pat" "$TMP" || true)"
  [ "$n" = "$WANT" ] || {
    echo "render: expected $WANT block(s) matching '$pat' but found $n — refusing"; exit 1; }
done

# The whole point of --staging: the plain-HTTP catch-all must SURVIVE alongside
# the TLS block. If a future edit drops it, the cutover silently goes back to
# having a total-outage window while the certificate issues, and nothing else
# here would catch that.
if [ "$STAGING" = "1" ]; then
  grep -qx ':80 {'                     "$TMP" || { echo "render: --staging lost the plain :80 catch-all — refusing"; exit 1; }
  grep -qx "https://$SITE_HOSTNAME {"  "$TMP" || { echo "render: --staging lost the https:// block — refusing"; exit 1; }
  # A redirect in the staging config would defeat the whole thing.
  if grep -q '^	redir ' "$TMP"; then
    echo "render: --staging must not emit a redirect — refusing"; exit 1
  fi
fi

# Syntax-check BEFORE it goes anywhere near the live file: a bad Caddyfile means
# `systemctl reload` fails and the old config keeps running, but a bad file that
# is already installed will take the site down on the next reboot.
if command -v caddy >/dev/null 2>&1; then
  caddy validate --adapter caddyfile --config "$TMP" >/dev/null 2>&1 \
    || { echo "render: caddy validate REJECTED the generated config — refusing"; caddy validate --adapter caddyfile --config "$TMP"; exit 1; }
fi

if [ "$STAGING" = "1" ]; then
  MODE="$SITE_HOSTNAME — TRANSIENT: plain :80 still serving while the cert issues"
elif [ -n "$SITE_HOSTNAME" ]; then
  MODE="$SITE_HOSTNAME (HTTPS)"
else
  MODE=":80 (plain HTTP)"
fi

if sudo test -f "$DEST" && sudo cmp -s "$TMP" "$DEST"; then
  echo "    Caddyfile already correct ($MODE) — not touching it"
  exit 0
fi

if sudo test -f "$DEST"; then
  BAK="$DEST.bak.$(date -u '+%Y%m%d-%H%M%S')"
  sudo cp -p "$DEST" "$BAK"
  echo "    backed up old Caddyfile -> $BAK"
fi
sudo cp "$TMP" "$DEST"
sudo chown root:root "$DEST"
sudo chmod 0644 "$DEST"
echo "    /etc/caddy/Caddyfile rendered for $MODE"

if [ "$RELOAD" = "1" ]; then
  sudo systemctl reload caddy 2>/dev/null || sudo systemctl restart caddy
  echo "    caddy reloaded"
fi
