#!/usr/bin/env bash
# =============================================================================
# One-time bootstrap on a FRESH Ubuntu 24.04 EC2 box (no Docker needed).
#   bash deploy/scripts/setup.sh
#
# PACKAGES ONLY: node 20 + pm2, postgresql-client, unzip, AWS CLI v2, Caddy.
# It does not build, migrate, start anything, or write /etc/caddy/Caddyfile.
#
# deploy/scripts/install.sh installs this same set itself (its step [2/8]), so
# this script is a convenience for a bare box and nothing more — install.sh is
# the deploy path, and the only supported way to put config on the box.
#
# It REFUSES to run on a box that is already serving the apps: see below. The
# steps it used to print at the end ended with
#     sudo cp deploy/Caddyfile /etc/caddy/Caddyfile && sudo systemctl reload caddy
# which on a box that has been cut over to HTTPS is the documented total-lockout:
# Caddy back on plain :80 while .env.production still says COOKIE_SECURE=true, so
# the Secure login cookie is never returned and nobody — including the operator —
# can sign in. deploy/Caddyfile is REFERENCE ONLY and is installed nowhere; the
# live config is generated by deploy/scripts/render-caddyfile.sh from
# deploy/site.env. That instruction is gone, and so are the other stale ones
# (`cd app` is not a directory in this repo, and migrate.sh + a bare `pm2 start`
# skip every gate install.sh applies).
# =============================================================================
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"     # deploy/
ROOT="$(cd "$HERE/.." && pwd)"               # repo root

# ── refuse to "bootstrap" a box that is already live ─────────────────────────
# This script is for a bare box. On a box that is already running the apps —
# above all one that has been cut over to HTTPS — the right tool is install.sh,
# which installs the same packages AND re-renders the Caddyfile from
# deploy/site.env instead of assuming plain :80. Refusing costs nothing (there
# is a working command below for every case); guessing costs payroll.
LIVE_REASONS=""
add_reason() { LIVE_REASONS="${LIVE_REASONS}    · $1
"; }

SITE_HOSTNAME=""
if [ -f "$HERE/site.env" ]; then
  # `|| true`: a grep that matches nothing exits 1, and this script runs under
  # `set -e -o pipefail`, so an empty SITE_HOSTNAME would abort the run here.
  SITE_HOSTNAME="$(grep -E '^[[:space:]]*SITE_HOSTNAME=' "$HERE/site.env" | tail -1 | cut -d= -f2- | tr -d "\"' \t\r" || true)"
fi
if [ -n "$SITE_HOSTNAME" ]; then
  add_reason "deploy/site.env says this box is served at https://$SITE_HOSTNAME"
fi
if [ -f "$ROOT/.env.production" ]; then
  # Same rule install.sh and enable-https.sh apply, for the same reason: an
  # EMPTY COOKIE_SECURE is not neutral. lib/aws/auth.js falls back to
  # NODE_ENV === "production", which .env.production itself sets, so blank still
  # means a Secure cookie — and a Secure cookie on a plain-:80 box is the lockout.
  CS_RAW="$(grep -E '^COOKIE_SECURE=' "$ROOT/.env.production" | tail -1 | cut -d= -f2- | awk '{print $1}' || true)"
  NE_RAW="$(grep -E '^NODE_ENV=' "$ROOT/.env.production" | tail -1 | cut -d= -f2- | awk '{print $1}' || true)"
  if [ "$CS_RAW" = "true" ]; then
    add_reason ".env.production has COOKIE_SECURE=true — this box expects HTTPS"
  elif [ -z "$CS_RAW" ] && [ "$NE_RAW" = "production" ]; then
    add_reason ".env.production leaves COOKIE_SECURE empty or absent, which falls back to
      NODE_ENV=production — i.e. a Secure cookie, i.e. this box expects HTTPS"
  fi
fi
# A hostname block in the LIVE config (`example.com {` or `https://example.com {`)
# means Caddy is serving TLS right now. A plain `:80 {` does not match, and
# neither do the `reverse_proxy 127.0.0.1:3009` lines inside a block.
if sudo test -f /etc/caddy/Caddyfile 2>/dev/null &&
   sudo grep -qE '^[[:space:]]*(https://)?[A-Za-z0-9_-]+(\.[A-Za-z0-9_-]+)+[[:space:]]*\{' /etc/caddy/Caddyfile 2>/dev/null; then
  add_reason "/etc/caddy/Caddyfile already serves a hostname, not plain :80"
fi
if command -v pm2 >/dev/null 2>&1 && pm2 describe ajace-timesheet >/dev/null 2>&1; then
  add_reason "pm2 is already running ajace-timesheet on this box"
fi

if [ -n "$LIVE_REASONS" ]; then
  cat >&2 <<EOF

    ✗ REFUSING — this is not a fresh box, and setup.sh is only for fresh boxes.

$LIVE_REASONS
      Nothing has been changed. What you want instead:

        deploy or re-deploy (installs the same packages, applies the schema,
        builds both apps beside the live build and swaps them in, and RENDERS
        /etc/caddy/Caddyfile from deploy/site.env):

          bash deploy/scripts/install.sh

        only re-write /etc/caddy/Caddyfile from deploy/site.env:

          bash deploy/scripts/render-caddyfile.sh

      NEVER  sudo cp deploy/Caddyfile /etc/caddy/Caddyfile.
      deploy/Caddyfile is REFERENCE ONLY — a plain :80 config. On a box serving
      HTTPS it puts Caddy back on plain HTTP while .env.production still says
      COOKIE_SECURE=true, so the Secure login cookie is never returned and
      NOBODY can sign in — and HSTS has already told browsers to refuse plain
      http for that hostname, for up to a year. There is no server-side undo.
      See deploy/docs/HTTPS-CUTOVER.md.

      If this really is a rebuilt box and you restored deploy/site.env or
      .env.production on purpose, that is fine and nothing is wrong: just run
      install.sh. It installs every package this script would have.

EOF
  exit 1
fi

echo "== Node 20 + pm2 =="
if ! command -v node >/dev/null 2>&1; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  sudo apt-get install -y nodejs
fi
sudo npm i -g pm2 >/dev/null 2>&1 || sudo npm i -g pm2

echo "== psql client + unzip + AWS CLI v2 + Caddy =="
sudo apt-get update -y
sudo apt-get install -y postgresql-client unzip debian-keyring debian-archive-keyring apt-transport-https curl
# Ubuntu 24.04 has no 'awscli' apt package — use the official v2 installer.
if ! command -v aws >/dev/null 2>&1; then
  case "$(uname -m)" in aarch64|arm64) AZ=aarch64;; *) AZ=x86_64;; esac
  curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-$AZ.zip" -o /tmp/awscliv2.zip
  unzip -q -o /tmp/awscliv2.zip -d /tmp && sudo /tmp/aws/install --update
  rm -rf /tmp/awscliv2.zip /tmp/aws
fi
if ! command -v caddy >/dev/null 2>&1; then
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
  sudo apt-get update -y && sudo apt-get install -y caddy
fi

cat <<'EOF'

Packages installed. Nothing has been built, started or configured yet.

Deploy with ONE command. It is also the deploy path for every later change:

  cp deploy/env.production.example .env.production   # then EDIT it
  chmod 600 .env.production
  bash deploy/scripts/install.sh

install.sh applies the schema to RDS, builds both apps into .next.build and
swaps them in (the live build is never touched), starts them under pm2 with
boot-on-reboot, installs the nightly backup and 5-minute health-check cron
jobs, and RENDERS /etc/caddy/Caddyfile from deploy/site.env by calling
deploy/scripts/render-caddyfile.sh — which is the only thing that writes that
file. It refuses to deploy a COOKIE_SECURE / hostname combination that would
lock everyone out, in either direction.

  ⚠ Do NOT 'sudo cp deploy/Caddyfile /etc/caddy/Caddyfile'. That file is
    REFERENCE ONLY (a plain :80 config) and is installed nowhere. Copying it
    over a box that serves HTTPS is the total-lockout state: plain HTTP with
    COOKIE_SECURE=true means the Secure cookie is never returned and nobody
    can sign in, and HSTS blocks the http fallback for up to a year.
    Change the hostname in deploy/site.env, the routing in
    render-caddyfile.sh, and apply either with:
      bash deploy/scripts/render-caddyfile.sh

  · make yourself admin:  deploy/scripts/make-admin.sh you@ajace.com
  · control the apps:     deploy/scripts/app.sh {start|stop|restart|status|logs}
  · HTTPS, when DNS is ready: read deploy/docs/HTTPS-CUTOVER.md first, then
      bash deploy/scripts/enable-https.sh <hostname> [acme-email]
EOF
